test commit
liveasy97/biddingApi pull request #1
Opened 2021-05-03 14:58 UTC by badireddisatyasaivarun

2021-05-07 19:55 UTC, pranavgupta001 commented on biddingApi/biddingApi/src/main/java/biddingApi/biddingApi/Controller/BiddingController.java
> +	@GetMapping("/bidding")
instead of bidding use bid

2021-05-07 20:28 UTC, pranavgupta001 commented on biddingApi/biddingApi/src/main/java/biddingApi/biddingApi/Controller/BiddingController.java
> +	public BidPostResponse addBid(@RequestBody BidPostRequest bidPostRequest)
{
    "transporterId":"transporterId:3265cbe9-fd73-451c-aafc-94525f801a19",
    "loadId":"load:3265cbe9-fd73-451c-aafc-94525f801a19",
    "rate":"100"
}
your response is 
{
    "status": "Failed: TransporterId and LoadId both cannot be assigned simulataneously"
}
loadId is  required but transporterId is optional if payload has both details then we need to add new entry

2021-05-09 11:13 UTC, jsrub requested changes

2021-05-09 11:13 UTC, jsrub commented on biddingApi/biddingApi/src/main/java/biddingApi/biddingApi/ErrorConstants/Constants.java
> +	private String success = "Success";
these variables should be static. so that you are able to use them without getters

2021-05-09 11:13 UTC, jsrub commented on biddingApi/biddingApi/src/main/java/biddingApi/biddingApi/Service/BiddingServiceImpl.java
> +	}
lets have some basic checks here

2021-05-09 11:13 UTC, jsrub commented on biddingApi/biddingApi/src/main/java/biddingApi/biddingApi/Service/BiddingServiceImpl.java
> +		return biddingDao.findById(id).get();
same comment as above

2021-05-09 11:13 UTC, jsrub commented on biddingApi/biddingApi/src/main/java/biddingApi/biddingApi/Service/BiddingServiceImpl.java
> +		return biddingDao.findAll();
please note that we never use findAll() even if we need to send all the bids we will send a paginated response. this wastes db calls. you should send paginated response.

2021-05-09 11:13 UTC, jsrub commented on biddingApi/biddingApi/src/main/java/biddingApi/biddingApi/Service/BiddingServiceImpl.java
> +			 response.setStatus(constants.getPLoadIdAndTransPorterIdAreNull());
use static variables in constants file.

2021-06-07 20:48 UTC, liveasy97 approved these changes

2021-06-07 20:48 UTC, merged